-- 1. TABLOLARIN OLUŞTURULMASI
CREATE TABLE ogrenciler (
    ogrenci_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad VARCHAR2(50),
    soyad VARCHAR2(50),
    bolum VARCHAR2(50)
);
CREATE TABLE notlar (
    not_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ogrenci_id NUMBER,
    ders_adi VARCHAR2(50),
    vize NUMBER,
    final NUMBER,
    ortalama NUMBER,
    durum VARCHAR2(10),
    FOREIGN KEY (ogrenci_id) REFERENCES ogrenciler(ogrenci_id)
);
