/*******************************************************************************
  PROJE ADI: Smart Inventory & Auto-Reorder System (Akıllı Stok Yönetimi)
  YAZAR: [Güneş Nur ÇETİN \@GunesNurCetin]
  TARİH: 2026-04-08
  
  AÇIKLAMA (TR): 
  Bu sistem, perakende sektöründe stok takibini otomatize eder. 
  Ürün stoğu kritik eşiğin altına düştüğünde, sistem otomatik olarak 
  bir 'Tedarik Talebi' oluşturur. Trigger ve Cursor kullanımı üzerine odaklanır.
  
  FEATURES (EN):
  - Automated Inventory Tracking: Real-time stock updates.
  - Smart Reordering: Automated supply requests via Triggers.
  - Batch Reporting: Monthly stock movement analysis using Cursors.
*******************************************************************************/

-- 1. SCHEMA SETUP (Tablo Yapılandırması)
-- -----------------------------------------------------------------------------
BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE supply_requests';
    EXECUTE IMMEDIATE 'DROP TABLE sales_history';
    EXECUTE IMMEDIATE 'DROP TABLE products';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE products (
    product_id NUMBER PRIMARY KEY,
    product_name VARCHAR2(100),
    stock_quantity NUMBER DEFAULT 0,
    min_threshold NUMBER DEFAULT 10, -- Kritik stok sınırı
    unit_price NUMBER(10, 2)
);

CREATE TABLE sales_history (
    sale_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER REFERENCES products(product_id),
    quantity_sold NUMBER,
    sale_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE supply_requests (
    request_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id NUMBER,
    request_amount NUMBER,
    request_date DATE DEFAULT SYSDATE,
    status VARCHAR2(20) DEFAULT 'PENDING'
);

-- 2. DUMMY DATA (Örnek Ürünler)
INSERT INTO products VALUES (501, 'Karton Bardak 8oz', 100, 20, 0.50);
INSERT INTO products VALUES (502, 'Karton Bardak 12oz', 15, 25, 0.75);
COMMIT;

-- 3. AUTO-REORDER TRIGGER (Otomatik Tedarik Tetikleyicisi)
-- -----------------------------------------------------------------------------
-- Stok güncellendiğinde (satış sonrası), miktar threshold'un altına düşerse
-- otomatik olarak tedarik tablosuna kayıt atar.
CREATE OR REPLACE TRIGGER trg_check_stock_levels
AFTER UPDATE OF stock_quantity ON products
FOR EACH ROW
WHEN (new.stock_quantity < new.min_threshold)
DECLARE
    v_exists NUMBER;
BEGIN
    -- Halihazırda bekleyen bir talep var mı kontrol et
    SELECT COUNT(*) INTO v_exists 
    FROM supply_requests 
    WHERE product_id = :new.product_id AND status = 'PENDING';

    IF v_exists = 0 THEN
        INSERT INTO supply_requests (product_id, request_amount, status)
        VALUES (:new.product_id, :new.min_threshold * 2, 'PENDING');
        
        DBMS_OUTPUT.PUT_LINE('UYARI: ' || :new.product_name || ' stoğu azaldı. Tedarik talebi oluşturuldu.');
    END IF;
END;
/

-- 4. INVENTORY MANAGEMENT PACKAGE (Yönetim Paketi)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE pkg_inventory_mgmt AS
    -- Satış işlemi gerçekleştirir
    PROCEDURE record_sale(p_prod_id NUMBER, p_qty NUMBER);
    
    -- Tüm ürünlerin durumunu raporlar (Cursor Kullanımı)
    PROCEDURE generate_stock_report;
END pkg_inventory_mgmt;
/

CREATE OR REPLACE PACKAGE BODY pkg_inventory_mgmt AS
    PROCEDURE record_sale(p_prod_id NUMBER, p_qty NUMBER) IS
    BEGIN
        -- Stok düşür
        UPDATE products 
        SET stock_quantity = stock_quantity - p_qty 
        WHERE product_id = p_prod_id;

        -- Satış geçmişine ekle
        INSERT INTO sales_history (product_id, quantity_sold) 
        VALUES (p_prod_id, p_qty);
        
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            DBMS_OUTPUT.PUT_LINE('Satis sirasinda hata: ' || SQLERRM);
    END record_sale;

    PROCEDURE generate_stock_report IS
        -- Cursor ile kritik durumdaki ürünleri çekiyoruz
        CURSOR c_stock IS 
            SELECT product_name, stock_quantity, min_threshold 
            FROM products;
        v_status VARCHAR2(20);
    BEGIN
        DBMS_OUTPUT.PUT_LINE('--- GÜNCEL STOK RAPORU ---');
        FOR r_item IN c_stock LOOP
            IF r_item.stock_quantity < r_item.min_threshold THEN
                v_status := '!!! KRITIK !!!';
            ELSE
                v_status := 'NORMAL';
            END IF;
            
            DBMS_OUTPUT.PUT_LINE('Ürün: ' || r_item.product_name || 
                                 ' | Stok: ' || r_item.stock_quantity || 
                                 ' | Durum: ' || v_status);
        END LOOP;
    END generate_stock_report;
END pkg_inventory_mgmt;
/

-- 5. TEST SENARYOSU
-- -----------------------------------------------------------------------------
SET SERVEROUTPUT ON;
BEGIN
    -- Normal bir satış (Stok 100 -> 90)
    pkg_inventory_mgmt.record_sale(501, 10);
    
    -- Kritik seviyeye düşüren satış (Stok 15 -> 5, Threshold 25 idi)
    -- Bu işlem otomatik olarak bir supply_request oluşturacaktır.
    pkg_inventory_mgmt.record_sale(502, 10);
    
    -- Raporu görüntüle
    pkg_inventory_mgmt.generate_stock_report;
END;
/

-- Sonuçları görüntülemek için:
SELECT * FROM supply_requests;
