/*******************************************************************************
  PROJE ADI: PL/SQL Advanced Banking System (Gelişmiş Bankacılık Sistemi)
  YAZAR: [Güneş Nur ÇETİN\@GunesNurCetin]
  TARİH: 2026-04-08
  
  AÇIKLAMA (TR): 
  Bu proje, kurumsal seviyede bir bankacılık işlem motorunu simüle eder. 
  Sistem; ACID prensiplerine uygun para transferi, dinamik loglama ve 
  hata yönetimini (Exception Handling) içerir.
  
  FEATURES (EN):
  - Atomic Transactions: Full rollback on failure.
  - Exception Management: Custom error handling for insufficient funds.
  - Logging: Automated auditing of all successful and failed transactions.
  - Concurrency Control: Uses 'SELECT FOR UPDATE' to prevent double-spending.
*******************************************************************************/

-- 1. SCHEMA SETUP (Tablo Yapılandırması)
-- -----------------------------------------------------------------------------
-- 'accounts' tablosu müşteri bakiyelerini tutar. 
-- 'transaction_logs' tüm işlem geçmişini ve hataları izlemek için kullanılır.

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE transaction_logs';
    EXECUTE IMMEDIATE 'DROP TABLE accounts';
EXCEPTION WHEN OTHERS THEN NULL; END;
/

CREATE TABLE accounts (
    account_id NUMBER PRIMARY KEY,
    account_holder VARCHAR2(100) NOT NULL,
    balance NUMBER(15, 2) DEFAULT 0 CHECK (balance >= 0) -- Negatif bakiye kontrolü
);

CREATE TABLE transaction_logs (
    log_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id NUMBER,
    action_type VARCHAR2(50),
    amount NUMBER(15, 2),
    log_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    status_message VARCHAR2(255)
);

-- 2. DUMMY DATA (Örnek Veri Seti)
INSERT INTO accounts (account_id, account_holder, balance) VALUES (101, 'Ahmet Yilmaz', 5000);
INSERT INTO accounts (account_id, account_holder, balance) VALUES (102, 'Ayse Demir', 2000);
COMMIT;

-- 3. BANKING PACKAGE SPECIFICATION (Paket Tanımı)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE pkg_bank_ops AS
    -- Özel Hata: Yetersiz bakiye durumu için tanımlanmıştır.
    insufficient_funds EXCEPTION;
    PRAGMA EXCEPTION_INIT(insufficient_funds, -20001);

    -- Transfer Prosedürü: Kaynak ve hedef hesap arasında güvenli transfer sağlar.
    PROCEDURE transfer_money(
        p_from_acc IN NUMBER,
        p_to_acc   IN NUMBER,
        p_amount   IN NUMBER
    );
END pkg_bank_ops;
/

-- 4. BANKING PACKAGE BODY (Paket Mantığı)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE PACKAGE BODY pkg_bank_ops AS
    PROCEDURE transfer_money(
        p_from_acc IN NUMBER,
        p_to_acc   IN NUMBER,
        p_amount   IN NUMBER
    ) IS
        v_current_balance NUMBER;
    BEGIN
        -- [Bakiye Kontrolü & Kilitleme]
        -- 'FOR UPDATE' kullanılarak işlem sırasında verinin değişmesi engellenir.
        SELECT balance INTO v_current_balance 
        FROM accounts 
        WHERE account_id = p_from_acc 
        FOR UPDATE;

        IF v_current_balance < p_amount THEN
            RAISE_APPLICATION_ERROR(-20001, 'Bakiye Yetersiz! Mevcut: ' || v_current_balance);
        END IF;

        -- [Transfer İşlemi]
        -- Gönderen hesaptan düş, alıcı hesaba ekle.
        UPDATE accounts SET balance = balance - p_amount WHERE account_id = p_from_acc;
        UPDATE accounts SET balance = balance + p_amount WHERE account_id = p_to_acc;

        -- [Başarılı İşlem Loglama]
        INSERT INTO transaction_logs (account_id, action_type, amount, status_message)
        VALUES (p_from_acc, 'TRANSFER_OUT', p_amount, 'SUCCESSFUL');

        COMMIT; -- Tüm işlemler başarılıysa kalıcı hale getir.
        DBMS_OUTPUT.PUT_LINE('Islem onaylandi: ' || p_amount || ' transfer edildi.');

    EXCEPTION
        WHEN OTHERS THEN
            -- Bir hata oluşursa (veritabanı hatası veya yetersiz bakiye)
            -- Yapılan tüm finansal değişiklikleri geri al (Rollback).
            ROLLBACK; 
            
            -- Hatayı log tablosuna kaydet (Otonom loglama simülasyonu).
            INSERT INTO transaction_logs (account_id, action_type, amount, status_message)
            VALUES (p_from_acc, 'TRANSFER_FAILED', p_amount, SUBSTR(SQLERRM, 1, 200));
            COMMIT;
            DBMS_OUTPUT.PUT_LINE('Hata: ' || SQLERRM);
    END transfer_money;
END pkg_bank_ops;
/

-- 5. EXECUTION & TESTING (Test Senaryoları)
-- -----------------------------------------------------------------------------
SET SERVEROUTPUT ON;
BEGIN
    -- Senaryo A: Geçerli Transfer
    DBMS_OUTPUT.PUT_LINE('--- Test 1: Gecerli Transfer ---');
    pkg_bank_ops.transfer_money(101, 102, 1000);
    
    -- Senaryo B: Hatalı Transfer (Yetersiz Bakiye)
    DBMS_OUTPUT.PUT_LINE('--- Test 2: Gecersiz Transfer (Bakiye Yetmiyor) ---');
    pkg_bank_ops.transfer_money(102, 101, 99999);
END;
/

-- Son durum kontrolü
SELECT * FROM accounts;
SELECT * FROM transaction_logs;
